version: '3.3'

services:
  db:
    image: minimal/database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      TZ: "Europe/Berlin"

  checker:
    image: minimal/checker
    environment:
      MariaDB_Adress: db
      MariaDB_Port: 3306
      MariaDB_User: checker
      MariaDB_PW: check4me
      MariaDB_Database: minimal
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
        window: 60s
    depends_on: 
      - db
